CAAssistant/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CAAssistant.Controllers
{
    public class ClientController : Controller
    {
        // GET: Client
        public ActionResult Index()
        {
            return View();
        }

    }

}

CAAssistant/Controllers/ClientFilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CAAssistant.DataStore;
using CAAssistant.Models;
using Microsoft.AspNet.Identity;
using MongoDB.Bson;
using MongoDB.Driver;

namespace CAAssistant.Controllers
{
    public class ClientFilesController : Controller
    {
        
        private readonly CaAssistantContext _assistantContext = new CaAssistantContext();

        // GET: ClientFiles
        public ActionResult Index()
        {
            var filter = Builders<ClientFile>.Filter.Exists("_id");
            var clientFilesList = _assistantContext.ClientFiles.FindAsync(filter).Result.ToListAsync().Result;
            return View(clientFilesList);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ClientFileViewModel clientFileView)
        {
            clientFileView.UserName = User.Identity.GetUserName();
            clientFileView.InitialFileStatus = new FileStatusModification
            {
                OldStatus = "New",
                NewStatus = "New",
                Description = "Started",
                ModifiedBy = clientFileView.UserName
            };

            var clientFile = new ClientFile(clientFileView);

            _assistantContext.ClientFiles.InsertOneAsync(clientFile).Wait();

            return RedirectToAction("Index");
        }

        
        public ActionResult Details(string id)
        {
            var clientFile = GetClientFile(id);
            return View(clientFile);
        }

        private ClientFile GetClientFile(string id)
        {
            var filter = Builders<ClientFile>.Filter.Eq("_id", new ObjectId(id));
            var clientFile = _assistantContext.ClientFiles.Find(filter).FirstOrDefaultAsync().Result;
            return clientFile;
        }

        public ActionResult Edit(string id)
        {
            var clientFile = GetClientFile(id);
            var clientFileView = new ClientFileViewModel(clientFile);
            return View(clientFileView);
        }

        [HttpPost]
        public ActionResult Edit(ClientFileViewModel clientFileView)
        {
            var filter = Builders<ClientFile>.Filter.Eq("_id", new ObjectId(clientFileView.Id));
            var clientFile = _assistantContext.ClientFiles.Find(filter).FirstOrDefaultAsync().Result;
            clientFileView.UserName = User.Identity.GetUserName();

            var filestatus = new FileStatusModification
            {
                OldStatus = clientFile.FileStatus,
                NewStatus = clientFileView.FileStatus,
                Description = "Review",
                ModifiedBy = clientFileView.UserName
            };
            clientFile.AddFileStatus(filestatus);

            var update = Builders<ClientFile>.Update
                .Set("FileStatusModifications", clientFile.FileStatusModifications)
                .Set("FileStatus", filestatus.NewStatus);
            var result = _assistantContext.ClientFiles.UpdateOneAsync(filter, update).Result;

            return RedirectToAction("Index");
        }

    }
}

CAAssistant/Views/Shared/_Layout.cshtml
@using System.Configuration
@{
    var applicationName = ConfigurationManager.AppSettings["ApplicationName"];
    var applicationVersion = ConfigurationManager.AppSettings["ApplicationVerion"];
    var developedBy = ConfigurationManager.AppSettings["DevelopedBy"];
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @applicationName</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/filetree")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CA Assistant", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Clients List", "Index", "Client")</li>
                        <li>@Html.ActionLink("Clients Files", "Index", "ClientFiles")</li>
                    }
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    <footer>
        <hr class="hr-layout" />
        <div class="float-left">
            <p>&copy; @DateTime.Now.Year - @developedBy (Version @applicationVersion).</p>
        </div>
    </footer>

</body>
</html>